import { Component } from '@angular/core';
import { TableColumn, AdvancedTable, TableConfig } from 'b2b-tools';

type UserRow = {
  id: number;
  name: string;
  age: number;
  salary: number;
  createdAt: string;
  avatarUrl: string;
  status: 'ACTIVO' | 'INACTIVO';
  profileUrl: string;
};

@Component({
  selector: 'app-advanced-table-demo',
  imports: [AdvancedTable],
  templateUrl: './advanced-table-demo.page.html',
  styleUrl: './advanced-table-demo.page.css',
})
export class AdvancedTableDemoPage {
  columns: TableColumn<UserRow>[] = [
    {
      key: 'avatarUrl',
      label: 'Avatar',
      type: 'image',
      size: 'SM',
      options: { image: { hidden: true, openInModal: true } },
    },
    {
      key: 'name',
      label: 'Nombre',
      type: 'string',
      size: 'AUTO',
      sortable: true,
      filterable: true,
    },
    {
      key: 'age',
      label: 'Edad',
      type: 'integer',
      size: 'SM',
      sortable: true,
      align: 'right',
      filterable: true,
    },
    {
      key: 'salary',
      label: 'Sueldo',
      type: 'currency',
      size: 'MD',
      sortable: true,
      align: 'right',
    },
    { key: 'createdAt', label: 'Alta', type: 'date', size: 'MD', sortable: true, filterable: true },
    {
      key: 'status',
      label: 'Estatus',
      type: 'status',
      size: 'SM',
      filterable: true,
      options: { status: { classMap: { ACTIVO: 'success', INACTIVO: 'error' } } },
    },
    {
      key: 'profileUrl',
      label: 'Perfil',
      type: 'link',
      size: 'AUTO',
      options: { link: { target: '_blank' } },
    },
    {
      key: 'actions',
      label: 'Acciones',
      type: 'actions',
      size: 'SM',
      align: 'center',
      actions: [
        { id: 'edit', label: 'Editar', icon: 'edit', tooltip: 'Editar', variant: 'default' },
        { id: 'delete', label: 'Eliminar', icon: 'delete', tooltip: 'Eliminar', variant: 'danger' },
      ],
    },
  ];

  rows: UserRow[] = [
    {
      id: 1,
      name: 'Luis Emiliano Cortés Camacho',
      age: 31,
      salary: 55000,
      createdAt: '2025-10-01',
      avatarUrl: 'https://picsum.photos/200',
      status: 'ACTIVO',
      profileUrl: 'https://example.com/u/1',
    },
    {
      id: 2,
      name: 'Ana Martínez López',
      age: 28,
      salary: 42000,
      createdAt: '2025-11-10',
      avatarUrl: 'https://picsum.photos/201',
      status: 'INACTIVO',
      profileUrl: 'https://example.com/u/2',
    },
    {
      id: 3,
      name: 'Carlos Hernández Ruiz',
      age: 35,
      salary: 62000,
      createdAt: '2025-09-18',
      avatarUrl: 'https://picsum.photos/202',
      status: 'ACTIVO',
      profileUrl: 'https://example.com/u/3',
    },
    {
      id: 4,
      name: 'María Fernanda Gómez',
      age: 24,
      salary: 32000,
      createdAt: '2025-12-02',
      avatarUrl: 'https://picsum.photos/203',
      status: 'ACTIVO',
      profileUrl: 'https://example.com/u/4',
    },
    {
      id: 5,
      name: 'Jorge Luis Ramírez',
      age: 41,
      salary: 78000,
      createdAt: '2024-07-21',
      avatarUrl: 'https://picsum.photos/204',
      status: 'INACTIVO',
      profileUrl: 'https://example.com/u/5',
    },
    {
      id: 6,
      name: 'Paola Sánchez Torres',
      age: 29,
      salary: 39000,
      createdAt: '2025-08-14',
      avatarUrl: 'https://picsum.photos/205',
      status: 'ACTIVO',
      profileUrl: 'https://example.com/u/6',
    },
    {
      id: 7,
      name: 'Ricardo Morales Díaz',
      age: 33,
      salary: 48000,
      createdAt: '2025-06-05',
      avatarUrl: 'https://picsum.photos/206',
      status: 'ACTIVO',
      profileUrl: 'https://example.com/u/7',
    },
    {
      id: 8,
      name: 'Valeria Ortega Cruz',
      age: 22,
      salary: 25000,
      createdAt: '2025-11-28',
      avatarUrl: 'https://picsum.photos/207',
      status: 'INACTIVO',
      profileUrl: 'https://example.com/u/8',
    },
    {
      id: 9,
      name: 'Fernando Castillo Vega',
      age: 38,
      salary: 67000,
      createdAt: '2024-12-15',
      avatarUrl: 'https://picsum.photos/208',
      status: 'ACTIVO',
      profileUrl: 'https://example.com/u/9',
    },
    {
      id: 10,
      name: 'Daniela Pérez Flores',
      age: 26,
      salary: 36000,
      createdAt: '2025-10-22',
      avatarUrl: 'https://picsum.photos/209',
      status: 'ACTIVO',
      profileUrl: 'https://example.com/u/10',
    },

    {
      id: 11,
      name: 'Miguel Ángel Navarro',
      age: 45,
      salary: 82000,
      createdAt: '2023-05-30',
      avatarUrl: 'https://picsum.photos/210',
      status: 'INACTIVO',
      profileUrl: 'https://example.com/u/11',
    },
    {
      id: 12,
      name: 'Sofía Mendoza Ríos',
      age: 27,
      salary: 41000,
      createdAt: '2025-09-09',
      avatarUrl: 'https://picsum.photos/211',
      status: 'ACTIVO',
      profileUrl: 'https://example.com/u/12',
    },
    {
      id: 13,
      name: 'Alejandro Cruz Peña',
      age: 34,
      salary: 53000,
      createdAt: '2025-03-17',
      avatarUrl: 'https://picsum.photos/212',
      status: 'ACTIVO',
      profileUrl: 'https://example.com/u/13',
    },
    {
      id: 14,
      name: 'Karla Jiménez Soto',
      age: 21,
      salary: 22000,
      createdAt: '2025-12-20',
      avatarUrl: 'https://picsum.photos/213',
      status: 'INACTIVO',
      profileUrl: 'https://example.com/u/14',
    },
    {
      id: 15,
      name: 'Héctor Iván Luna',
      age: 39,
      salary: 71000,
      createdAt: '2024-10-08',
      avatarUrl: 'https://picsum.photos/214',
      status: 'ACTIVO',
      profileUrl: 'https://example.com/u/15',
    },
    {
      id: 16,
      name: 'Brenda Aguilar Núñez',
      age: 30,
      salary: 45000,
      createdAt: '2025-07-11',
      avatarUrl: 'https://picsum.photos/215',
      status: 'ACTIVO',
      profileUrl: 'https://example.com/u/16',
    },
    {
      id: 17,
      name: 'Iván Torres Molina',
      age: 36,
      salary: 60000,
      createdAt: '2024-11-03',
      avatarUrl: 'https://picsum.photos/216',
      status: 'INACTIVO',
      profileUrl: 'https://example.com/u/17',
    },
    {
      id: 18,
      name: 'Lucía Paredes Cano',
      age: 23,
      salary: 28000,
      createdAt: '2025-11-01',
      avatarUrl: 'https://picsum.photos/217',
      status: 'ACTIVO',
      profileUrl: 'https://example.com/u/18',
    },
    {
      id: 19,
      name: 'Oscar Villegas Rocha',
      age: 42,
      salary: 76000,
      createdAt: '2023-09-19',
      avatarUrl: 'https://picsum.photos/218',
      status: 'INACTIVO',
      profileUrl: 'https://example.com/u/19',
    },
    {
      id: 20,
      name: 'Camila Estrada León',
      age: 25,
      salary: 34000,
      createdAt: '2025-10-30',
      avatarUrl: 'https://picsum.photos/219',
      status: 'ACTIVO',
      profileUrl: 'https://example.com/u/20',
    },

    {
      id: 21,
      name: 'Roberto Salinas Fuentes',
      age: 48,
      salary: 88000,
      createdAt: '2022-04-12',
      avatarUrl: 'https://picsum.photos/220',
      status: 'ACTIVO',
      profileUrl: 'https://example.com/u/21',
    },
    {
      id: 22,
      name: 'Andrea Lozano Rivas',
      age: 32,
      salary: 52000,
      createdAt: '2025-05-07',
      avatarUrl: 'https://picsum.photos/221',
      status: 'ACTIVO',
      profileUrl: 'https://example.com/u/22',
    },
    {
      id: 23,
      name: 'Diego Carrillo Méndez',
      age: 27,
      salary: 38000,
      createdAt: '2025-08-26',
      avatarUrl: 'https://picsum.photos/222',
      status: 'INACTIVO',
      profileUrl: 'https://example.com/u/23',
    },
    {
      id: 24,
      name: 'Natalia Rojas Beltrán',
      age: 34,
      salary: 56000,
      createdAt: '2024-06-18',
      avatarUrl: 'https://picsum.photos/223',
      status: 'ACTIVO',
      profileUrl: 'https://example.com/u/24',
    },
    {
      id: 25,
      name: 'Eduardo Neri Campos',
      age: 29,
      salary: 41000,
      createdAt: '2025-09-02',
      avatarUrl: 'https://picsum.photos/224',
      status: 'ACTIVO',
      profileUrl: 'https://example.com/u/25',
    },
    {
      id: 26,
      name: 'Renata Solís Quintana',
      age: 22,
      salary: 24000,
      createdAt: '2025-12-11',
      avatarUrl: 'https://picsum.photos/225',
      status: 'INACTIVO',
      profileUrl: 'https://example.com/u/26',
    },
    {
      id: 27,
      name: 'Francisco Ledezma Ortiz',
      age: 37,
      salary: 65000,
      createdAt: '2024-02-09',
      avatarUrl: 'https://picsum.photos/226',
      status: 'ACTIVO',
      profileUrl: 'https://example.com/u/27',
    },
    {
      id: 28,
      name: 'Paulina Vera Montoya',
      age: 31,
      salary: 47000,
      createdAt: '2025-04-15',
      avatarUrl: 'https://picsum.photos/227',
      status: 'ACTIVO',
      profileUrl: 'https://example.com/u/28',
    },
    {
      id: 29,
      name: 'Sergio Padilla Cortés',
      age: 44,
      salary: 79000,
      createdAt: '2023-08-01',
      avatarUrl: 'https://picsum.photos/228',
      status: 'INACTIVO',
      profileUrl: 'https://example.com/u/29',
    },
    {
      id: 30,
      name: 'Mónica Castañeda Gil',
      age: 26,
      salary: 35000,
      createdAt: '2025-10-05',
      avatarUrl: 'https://picsum.photos/229',
      status: 'ACTIVO',
      profileUrl: 'https://example.com/u/30',
    },

    {
      id: 31,
      name: 'Raúl Benítez Zamora',
      age: 40,
      salary: 72000,
      createdAt: '2024-09-27',
      avatarUrl: 'https://picsum.photos/230',
      status: 'ACTIVO',
      profileUrl: 'https://example.com/u/31',
    },
    {
      id: 32,
      name: 'Liliana Rosas Ponce',
      age: 28,
      salary: 43000,
      createdAt: '2025-06-30',
      avatarUrl: 'https://picsum.photos/231',
      status: 'ACTIVO',
      profileUrl: 'https://example.com/u/32',
    },
    {
      id: 33,
      name: 'Tomás Hidalgo Peralta',
      age: 35,
      salary: 61000,
      createdAt: '2024-01-14',
      avatarUrl: 'https://picsum.photos/232',
      status: 'INACTIVO',
      profileUrl: 'https://example.com/u/33',
    },
    {
      id: 34,
      name: 'Elena Muñoz Calderón',
      age: 23,
      salary: 27000,
      createdAt: '2025-11-19',
      avatarUrl: 'https://picsum.photos/233',
      status: 'ACTIVO',
      profileUrl: 'https://example.com/u/34',
    },
    {
      id: 35,
      name: 'Julián Ochoa Reyes',
      age: 46,
      salary: 85000,
      createdAt: '2022-12-03',
      avatarUrl: 'https://picsum.photos/234',
      status: 'INACTIVO',
      profileUrl: 'https://example.com/u/35',
    },
    {
      id: 36,
      name: 'Pamela Figueroa Salgado',
      age: 30,
      salary: 46000,
      createdAt: '2025-03-22',
      avatarUrl: 'https://picsum.photos/235',
      status: 'ACTIVO',
      profileUrl: 'https://example.com/u/36',
    },
    {
      id: 37,
      name: 'Emilio Rentería Solano',
      age: 34,
      salary: 54000,
      createdAt: '2024-05-16',
      avatarUrl: 'https://picsum.photos/236',
      status: 'ACTIVO',
      profileUrl: 'https://example.com/u/37',
    },
    {
      id: 38,
      name: 'Claudia Nieto Vargas',
      age: 27,
      salary: 39000,
      createdAt: '2025-08-08',
      avatarUrl: 'https://picsum.photos/237',
      status: 'INACTIVO',
      profileUrl: 'https://example.com/u/38',
    },
    {
      id: 39,
      name: 'Mauricio Acosta Belén',
      age: 43,
      salary: 74000,
      createdAt: '2023-10-25',
      avatarUrl: 'https://picsum.photos/238',
      status: 'ACTIVO',
      profileUrl: 'https://example.com/u/39',
    },
    {
      id: 40,
      name: 'Regina Palma Escobedo',
      age: 24,
      salary: 30000,
      createdAt: '2025-12-01',
      avatarUrl: 'https://picsum.photos/239',
      status: 'ACTIVO',
      profileUrl: 'https://example.com/u/40',
    },
  ];

  config: TableConfig = {
    globalSearch: true,
    columnFilters: true,
    selectable: true,
    selectionMode: 'multiple',
    pagination: { enabled: true, pageSize: 10, pageSizeOptions: [10, 25, 50] },
    scroll: { mode: 'none', heightPx: 420 },
    emptyText: 'No hay datos',
    rowIdKey: 'id',
  };

  onSelection(ids: Array<string | number>) {
    console.log('selected ids', ids);
  }

  onRowClick(row: UserRow) {
    console.log('row click', row);
  }

  onAction(ev: { actionId: string; row: any }) {
    console.log(ev);
  }
}
